[package]
name = "ywpm"
version = "1.2.6"
description = "YoRHa Wallpaper Manager. A simple console tool for easy management of your wallpapers."
authors = ["Petr <petrwinch-code@mail.ru>"]
repository = "https://github.com/petr590/ywpm"
license = "GPL-3.0-or-later"
edition = "2024"

[package.metadata.deb]
maintainer = "Petr <petrwinch-code@mail.ru>"
license-file = "LICENSE.txt"
extended-description = """\
YoRHa Wallpaper Manager. A simple console tool for easy management of your wallpapers.
YoRHa Wallpaper Manager is a modern, user-friendly command-line tool that helps \
you manage all your wallpapers on Linux. Please note that YWpM only determines \
when and which wallpapers to render, it doesn’t render the wallpapers itself. \
Instead, YWpM uses a backend. Currently, only mpvpaper is supported as a backend.\
"""
assets = [
    ["target/release/ywpmd",  "usr/libexec/ywpmd",                  "755"],
    ["target/release/ywpm",   "usr/bin/ywpm",                       "755"],
    ["systemd/ywpmd-pre.sh",  "usr/libexec/ywpmd-pre.sh",           "755"],
    ["systemd/ywpmd.service", "usr/lib/systemd/user/ywpmd.service", "644"],
    
    ["completions/ywpm.bash", "usr/share/bash-completion/completions/ywpm",    "644"],
    ["completions/_ywpm",     "usr/share/zsh/vendor-completions/_ywpm",        "644"],
    ["completions/ywpm.fish", "usr/share/fish/vendor-completions.d/ywpm.fish", "644"],
    ["completions/ywpm.elv",  "usr/share/elvish/lib/ywpm.elv",                 "644"],
]

[package.metadata.deb.variants.ru]
extended-description = """\
Менеджер обоев YoRHa. Простой консольный инструмент для лёгкого управления обоями.
YoRHa Wallpaper Manager — это современный, удобный консольный инструмент, который \
помогает управлять всеми вашими обоями в Linux. Обратите внимание, что YWpM только \
определяет, когда и какие обои реднерить, а не рендерит обои самостоятельно. \
Вместо этого YWpM использует бэкенд. На данный момент в качестве бэкенда \
поддерживается только mpvpaper.\
"""

[package.metadata.generate-rpm]
summary = """\
YoRHa Wallpaper Manager. A simple console tool for easy management of your wallpapers.
YoRHa Wallpaper Manager is a modern, user-friendly command-line tool that helps \
you manage all your wallpapers on Linux. Please note that YWpM only determines \
when and which wallpapers to render, it doesn’t render the wallpapers itself. \
Instead, YWpM uses a backend. Currently, only mpvpaper is supported as a backend.\
"""
assets = [
    { source = "target/release/ywpmd",  dest = "/usr/libexec/ywpmd",                  mode = "0755" },
    { source = "target/release/ywpm",   dest = "/usr/bin/ywpm",                       mode = "0755" },
    { source = "systemd/ywpmd-pre.sh",  dest = "/usr/libexec/ywpmd-pre.sh",           mode = "0755" },
    { source = "systemd/ywpmd.service", dest = "/usr/lib/systemd/user/ywpmd.service", mode = "0644" },
    { source = "LICENSE.txt",           dest = "/usr/share/doc/ywpm/LICENSE",         mode = "0644" },
    
    { source = "completions/ywpm.bash", dest = "usr/share/bash-completion/completions/ywpm",    mode = "0644" },
    { source = "completions/_ywpm",     dest = "usr/share/zsh/vendor-completions/_ywpm",        mode = "0644" },
    { source = "completions/ywpm.fish", dest = "usr/share/fish/vendor-completions.d/ywpm.fish", mode = "0644" },
    { source = "completions/ywpm.elv",  dest = "usr/share/elvish/lib/ywpm.elv",                 mode = "0644" },
]


[dependencies]
chrono          = { version = "0.4", features = ["unstable-locales"] }
clap            = { version = "4.6", features = ["derive"] }
clap_complete   = { version = "4.6", features = ["unstable-dynamic"] }
const-str       = "1.1"
display-info    = "0.5"
ffprobe         = "0.4"
imagesize       = "0.15"
indexmap        = "2.14"
indoc           = "2.0"
itertools       = "0.15"
nix             = { version = "0.31", features = ["poll", "signal"] }
once_cell       = "1.21"
path-absolutize = "4.0"
phf             = { version = "0.14", features = ["macros"] }
sd-notify       = "0.5"
serde           = { version = "1.0", features = ["rc"] }
serde_with      = { version = "3.23", features = ["chrono"] }
shlex           = "2.0"
walkdir         = "2.5"
yaml_serde      = { version = "0.10", default-features = false }

[dependencies.rand]
version = "0.10"
default-features = false
features = ["thread_rng"]

[dependencies.regex]
version = "1.13"
default-features = false
features = ["std", "perf"]


# [build-dependencies]
# chrono          = { version = "0.4", features = ["unstable-locales"] }
# clap_complete = "4.6"
# once_cell       = "1.21"

# [build-dependencies.regex]
# version = "1.13"
# default-features = false
# features = ["std", "perf"]


[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"

[[bin]]
name = "ywpmd"
path = "src/daemon/main.rs"

[[bin]]
name = "ywpm"
path = "src/client/main.rs"

[[bench]]
name = "socket_benches"
harness = false

[[bench]]
name = "canonicalize_benches"
harness = false
